name: Test MacOS Install Script with new Release

on:
  workflow_run:
    workflows: ["MetaCall Distributable MacOS Release"]
    types:
      - completed
    branches: ['v*.*.*']
  
jobs:
    test:
      runs-on: ubuntu-latest
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      steps:
        - uses: convictional/trigger-workflow-and-wait@v1.6.1
          with:
            owner: metacall
            repo: install
            github_token: ${{ secrets.G_PERSONAL_ACCESS_TOKEN }}
            workflow_file_name: test-macos.yml
            wait_workflow: true
            ref: master
