name: MetaCall Distributable macOS Test

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: ./install.sh
      - name: Test
        run: ./test.sh